# Generated by Django 3.0 on 2020-01-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='...', max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='imgUrl',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
