# Generated by Django 3.0 on 2020-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20200103_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='leftVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='middleVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rightVotes',
            field=models.IntegerField(default=0),
        ),
    ]
