# Generated by Django 3.0 on 2020-01-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20200103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='...', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article Title', max_length=200, null=True),
        ),
    ]
